=== Encore-Post-Sales/airbyte-magnify/airbyte-integrations/connectors/source-jira-data-center/source_jira_data_center/schemas/issue_votes.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "self": {
      "description": "The URL of these issue vote details.",
      "type": "string",
      "readOnly": true
    },
    "issueId": {
      "description": "Id of the related issue.",
      "type": ["null", "string"],
      "readOnly": true
    },
    "votes": {
      "description": "The number of votes on the issue.",
      "type": "integer",
      "readOnly": true
    },
    "hasVoted": {
      "description": "Whether the user making this request has voted on the issue.",
      "type": "boolean",
      "readOnly": true
    },
    "voters": {
      "description": "List of the users who have voted on this issue. An empty list is returned when the calling user doesn't have the *View voters and watchers* project permission.",
      "type": "array",
      "readOnly": true,
      "items": {
        "type": "object",
        "properties": {
          "self": {
            "description": "The URL of the user.",
            "type": "string",
            "readOnly": true
          },
          "key": {
            "description": "Optional; may be absent in some Data Center versions. See [Data Center REST API](https://developer.atlassian.com/server/jira/platform/rest/v10002/intro/).",
            "type": "string"
          },
          "accountId": {
            "description": "The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*. Required in requests.",
            "maxLength": 128,
            "type": "string"
          },
          "accountType": {
            "description": "The user account type. Can take the following values:\n\n *  `atlassian` regular Atlassian user account\n *  `app` system account used for Connect applications and OAuth to represent external systems\n *  `customer` Jira Service Desk account representing an external service desk",
            "type": "string",
            "readOnly": true,
            "enum": ["atlassian", "app", "customer", "unknown"]
          },
          "name": {
            "description": "Optional; may be absent in some Data Center versions. See [Data Center REST API](https://developer.atlassian.com/server/jira/platform/rest/v10002/intro/).",
            "type": "string"
          },
          "emailAddress": {
            "description": "The email address of the user. Depending on the user's privacy setting, this may be returned as null.",
            "type": "string",
            "readOnly": true
          },
          "avatarUrls": {
            "description": "The avatars of the user.",
            "readOnly": true,
            "type": "object",
            "properties": {
              "16x16": {
                "description": "The URL of the item's 16x16 pixel avatar.",
                "type": "string"
              },
              "24x24": {
                "description": "The URL of the item's 24x24 pixel avatar.",
                "type": "string"
              },
              "32x32": {
                "description": "The URL of the item's 32x32 pixel avatar.",
                "type": "string"
              },
              "48x48": {
                "description": "The URL of the item's 48x48 pixel avatar.",
                "type": "string"
              }
            }
          },
          "displayName": {
            "description": "The display name of the user. Depending on the user's privacy setting, this may return an alternative value.",
            "type": "string",
            "readOnly": true
          },
          "active": {
            "description": "Whether the user is active.",
            "type": "boolean",
            "readOnly": true
          },
          "timeZone": {
            "description": "The time zone specified in the user's profile. Depending on the user's privacy setting, this may be returned as null.",
            "type": "string",
            "readOnly": true
          },
          "locale": {
            "description": "The locale of the user. Depending on the user's privacy setting, this may be returned as null.",
            "type": "string",
            "readOnly": true
          },
          "groups": {
            "description": "The groups that the user belongs to.",
            "readOnly": true,
            "type": "object",
            "properties": {
              "size": {
                "description": "Size XML information.",
                "type": "integer",
                "xml": {
                  "attribute": true
                }
              },
              "items": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "description": "The name of group.",
                      "type": "string"
                    },
                    "self": {
                      "description": "The URL for these group details.",
                      "type": "string",
                      "readOnly": true
                    }
                  }
                }
              },
              "pagingCallback": {
                "description": "Paging callback.",
                "type": "object"
              },
              "callback": {
                "description": "Callback information.",
                "type": "object"
              },
              "max-results": {
                "description": "Max results related information.",
                "type": "integer",
                "xml": {
                  "name": "max-results",
                  "attribute": true
                }
              }
            }
          },
          "applicationRoles": {
            "description": "The application roles the user is assigned to.",
            "readOnly": true,
            "type": "object",
            "properties": {
              "size": {
                "description": "Size XML information.",
                "type": "integer",
                "xml": {
                  "attribute": true
                }
              },
              "items": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "description": "The key of the application role.",
                      "type": "string"
                    },
                    "groups": {
                      "description": "The groups associated with the application role.",
                      "uniqueItems": true,
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "name": {
                      "description": "The display name of the application role.",
                      "type": "string"
                    },
                    "defaultGroups": {
                      "description": "The groups that are granted default access for this application role.",
                      "uniqueItems": true,
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "selectedByDefault": {
                      "description": "Determines whether this application role should be selected by default on user creation.",
                      "type": "boolean"
                    },
                    "defined": {
                      "description": "Optional; may be absent in some Data Center versions.",
                      "type": "boolean"
                    },
                    "numberOfSeats": {
                      "description": "The maximum count of users on your license.",
                      "type": "integer"
                    },
                    "remainingSeats": {
                      "description": "The count of users remaining on your license.",
                      "type": "integer"
                    },
                    "userCount": {
                      "description": "The number of users counting against your license.",
                      "type": "integer"
                    },
                    "userCountDescription": {
                      "description": "The type of users being counted against your license.",
                      "type": "string"
                    },
                    "hasUnlimitedSeats": {
                      "description": "Indicates if there are unlimited seats for this application role.",
                      "type": "boolean"
                    },
                    "platform": {
                      "description": "Indicates if the application role belongs to Jira platform (`jira-core`).",
                      "type": "boolean"
                    }
                  }
                }
              },
              "pagingCallback": {
                "description": "Paging callback.",
                "type": "object"
              },
              "callback": {
                "description": "Callback information.",
                "type": "object"
              },
              "max-results": {
                "description": "Max results related information.",
                "type": "integer",
                "xml": {
                  "name": "max-results",
                  "attribute": true
                }
              }
            }
          },
          "expand": {
            "description": "Expand options that include additional user details in the response.",
            "type": "string",
            "readOnly": true,
            "xml": {
              "attribute": true
            }
          }
        }
      }
    }
  },
  "additionalProperties": true,
  "description": "The details of votes on an issue."
}

=== Encore-Post-Sales/airbyte-magnify/airbyte-integrations/connectors/source-jira-data-center/unit_tests/responses/issue_votes.json
{
  "self": "https://your-domain.atlassian.net/rest/api/issue/MKY-1/votes",
  "votes": 24,
  "hasVoted": true,
  "voters": [
    {
      "self": "https://your-domain.atlassian.net/rest/api/2/user?accountId=5b10a2844c20165700ede21g",
      "key": "",
      "accountId": "5b10a2844c20165700ede21g",
      "accountType": "atlassian",
      "name": "",
      "avatarUrls": {
        "48x48": "https://avatar-management--avatars.server-location.prod.public.atl-paas.net/initials/MK-5.png?size=48&s=48",
        "24x24": "https://avatar-management--avatars.server-location.prod.public.atl-paas.net/initials/MK-5.png?size=24&s=24",
        "16x16": "https://avatar-management--avatars.server-location.prod.public.atl-paas.net/initials/MK-5.png?size=16&s=16",
        "32x32": "https://avatar-management--avatars.server-location.prod.public.atl-paas.net/initials/MK-5.png?size=32&s=32"
      },
      "displayName": "Mia Krystof",
      "active": false
    }
  ]
}
