=== Encore-Post-Sales/airbyte-magnify/airbyte-integrations/connectors/source-jira-data-center/source_jira_data_center/schemas/users.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "self": {
      "description": "The URL of the user.",
      "type": "string",
      "readOnly": true
    },
    "key": {
      "description": "User key/identifier. Valid in Data Center v2. See [Data Center REST API](https://developer.atlassian.com/server/jira/platform/rest/v10002/intro/).",
      "type": "string"
    },
    "accountId": {
      "description": "The account ID of the user when present. Data Center v2 may return key/name instead.",
      "maxLength": 128,
      "type": "string"
    },
    "accountType": {
      "description": "The user account type. Can be one of: \n- `atlassian`: regular Atlassian user account \n- `app`: system account used for Connect applications and OAuth \n- `customer`: Jira Service Desk account representing an external service desk",
      "type": "string",
      "readOnly": true,
      "enum": ["atlassian", "app", "customer", "unknown"]
    },
    "name": {
      "description": "User name. Valid in Data Center v2. See [Data Center REST API](https://developer.atlassian.com/server/jira/platform/rest/v10002/intro/).",
      "type": "string"
    },
    "emailAddress": {
      "description": "The email address of the user. May be null based on privacy settings.",
      "type": "string",
      "readOnly": true
    },
    "avatarUrls": {
      "description": "The avatars of the user.",
      "readOnly": true,
      "type": "object",
      "properties": {
        "16x16": {
          "description": "The URL of the 16x16 pixel avatar.",
          "type": "string"
        },
        "24x24": {
          "description": "The URL of the 24x24 pixel avatar.",
          "type": "string"
        },
        "32x32": {
          "description": "The URL of the 32x32 pixel avatar.",
          "type": "string"
        },
        "48x48": {
          "description": "The URL of the 48x48 pixel avatar.",
          "type": "string"
        }
      }
    },
    "displayName": {
      "description": "The display name of the user. May return an alternative value based on privacy settings.",
      "type": "string",
      "readOnly": true
    },
    "active": {
      "description": "Indicates whether the user is active.",
      "type": "boolean",
      "readOnly": true
    },
    "timeZone": {
      "description": "The time zone specified in the user's profile. May be null based on privacy settings.",
      "type": "string",
      "readOnly": true
    },
    "locale": {
      "description": "The locale of the user. May be null based on privacy settings.",
      "type": "string",
      "readOnly": true
    },
    "groups": {
      "description": "The groups to which the user belongs.",
      "readOnly": true,
      "type": "object",
      "properties": {
        "size": {
          "description": "The size of the groups.",
          "type": "integer",
          "xml": {
            "attribute": true
          }
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "description": "The name of the group.",
                "type": "string"
              },
              "self": {
                "description": "The URL for group details.",
                "type": "string",
                "readOnly": true
              }
            }
          }
        },
        "pagingCallback": {
          "description": "The callback for pagination.",
          "type": "object"
        },
        "callback": {
          "description": "The callback for fetching more groups.",
          "type": "object"
        },
        "max-results": {
          "description": "The maximum number of results to be returned.",
          "type": "integer",
          "xml": {
            "name": "max-results",
            "attribute": true
          }
        }
      }
    },
    "applicationRoles": {
      "description": "The application roles assigned to the user.",
      "readOnly": true,
      "type": "object",
      "properties": {
        "size": {
          "description": "The size of the application roles.",
          "type": "integer",
          "xml": {
            "attribute": true
          }
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "key": {
                "description": "The key of the application role.",
                "type": "string"
              },
              "groups": {
                "description": "The groups associated with the application role.",
                "uniqueItems": true,
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "name": {
                "description": "The display name of the application role.",
                "type": "string"
              },
              "defaultGroups": {
                "description": "The groups granted default access for this application role.",
                "uniqueItems": true,
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "selectedByDefault": {
                "description": "Specifies if this application role should be selected by default on user creation.",
                "type": "boolean"
              },
              "defined": {
                "description": "Optional; may be absent in some Data Center versions.",
                "type": "boolean"
              },
              "numberOfSeats": {
                "description": "The maximum user count on the license.",
                "type": "integer"
              },
              "remainingSeats": {
                "description": "The remaining user count on the license.",
                "type": "integer"
              },
              "userCount": {
                "description": "The number of users counting against the license.",
                "type": "integer"
              },
              "userCountDescription": {
                "description": "The type of users being counted against the license.",
                "type": "string"
              },
              "hasUnlimitedSeats": {
                "description": "Indicates if the application role has unlimited seats.",
                "type": "boolean"
              },
              "platform": {
                "description": "Indicates if the application role belongs to Jira platform (`jira-core`).",
                "type": "boolean"
              }
            }
          }
        },
        "pagingCallback": {
          "description": "The callback for pagination.",
          "type": "object"
        },
        "callback": {
          "description": "The callback for fetching more application roles.",
          "type": "object"
        },
        "max-results": {
          "description": "The maximum number of results to be returned.",
          "type": "integer",
          "xml": {
            "name": "max-results",
            "attribute": true
          }
        }
      }
    },
    "expand": {
      "description": "Options to include additional user details in the response.",
      "type": "string",
      "readOnly": true,
      "xml": {
        "attribute": true
      }
    }
  },
  "additionalProperties": true,
  "description": "A user. Data Center v2 may return key/name and optionally accountId. See [Data Center REST API](https://developer.atlassian.com/server/jira/platform/rest/v10002/intro/).",
  "xml": {
    "name": "user"
  }
}

=== Encore-Post-Sales/airbyte-magnify/airbyte-integrations/connectors/source-jira-data-center/unit_tests/responses/users_groups_detailed.json
[
  {
    "self": "https://airbyteio.atlassian.net/rest/api/2/user?accountId=5fc9e78d2730d800760becc4",
    "accountId": "5fc9e78d2730d800760becc4",
    "accountType": "atlassian",
    "emailAddress": "integration-test@airbyte.io",
    "avatarUrls": {
      "48x48": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "24x24": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "16x16": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "32x32": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png"
    },
    "displayName": "integration test",
    "active": true,
    "timeZone": "America/Los_Angeles",
    "locale": "en_US",
    "groups": {
      "size": 27,
      "items": [
        {
          "name": "administrators",
          "groupId": "0ca6e087-7a61-4986-a269-98fe268854a1",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=0ca6e087-7a61-4986-a269-98fe268854a1"
        },
        {
          "name": "confluence-users",
          "groupId": "38d808e9-113f-45c4-817b-099e953b687a",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=38d808e9-113f-45c4-817b-099e953b687a"
        },
        {
          "name": "integration-test-group",
          "groupId": "5f1ec851-f8da-4f90-ab42-8dc50a9f99d8",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=5f1ec851-f8da-4f90-ab42-8dc50a9f99d8"
        },
        {
          "name": "jira-administrators",
          "groupId": "58582f33-a5a6-43b9-92a6-ff0bbacb49ae",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=58582f33-a5a6-43b9-92a6-ff0bbacb49ae"
        },
        {
          "name": "jira-software-users",
          "groupId": "4452b254-035d-469a-a422-1f4666dce50e",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=4452b254-035d-469a-a422-1f4666dce50e"
        },
        {
          "name": "jira-users",
          "groupId": "2513da2e-08cf-4415-9bcd-cbbd32fa227d",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=2513da2e-08cf-4415-9bcd-cbbd32fa227d"
        },
        {
          "name": "site-admins",
          "groupId": "76dad095-fc1a-467a-88b4-fde534220985",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=76dad095-fc1a-467a-88b4-fde534220985"
        },
        {
          "name": "Test group 0",
          "groupId": "ee8d15d1-6462-406a-b0a6-8065b7e4cdd7",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=ee8d15d1-6462-406a-b0a6-8065b7e4cdd7"
        },
        {
          "name": "Test group 1",
          "groupId": "bda1faf1-1a1a-42d1-82e4-a428c8b8f67c",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=bda1faf1-1a1a-42d1-82e4-a428c8b8f67c"
        },
        {
          "name": "Test group 10",
          "groupId": "e9f74708-e33c-4158-919d-6457f50c6e74",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=e9f74708-e33c-4158-919d-6457f50c6e74"
        },
        {
          "name": "Test group 11",
          "groupId": "b0e6d76f-701a-4208-a88d-4478f242edde",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=b0e6d76f-701a-4208-a88d-4478f242edde"
        },
        {
          "name": "Test group 12",
          "groupId": "dddc24a0-ef00-407e-abef-5a660b6f55cf",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=dddc24a0-ef00-407e-abef-5a660b6f55cf"
        },
        {
          "name": "Test group 13",
          "groupId": "dbe4af74-8387-4b08-843b-86af78dd738e",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=dbe4af74-8387-4b08-843b-86af78dd738e"
        },
        {
          "name": "Test group 14",
          "groupId": "d4570a20-38d8-44cc-a63b-0924d0d0d0ff",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=d4570a20-38d8-44cc-a63b-0924d0d0d0ff"
        },
        {
          "name": "Test group 15",
          "groupId": "87bde5c0-7231-44a7-88b5-421da2ab8052",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=87bde5c0-7231-44a7-88b5-421da2ab8052"
        },
        {
          "name": "Test group 16",
          "groupId": "538b6aa2-bf57-402f-93c0-c2e2d68b7155",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=538b6aa2-bf57-402f-93c0-c2e2d68b7155"
        },
        {
          "name": "Test group 17",
          "groupId": "022bc924-ac57-442d-80c9-df042b73ad87",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=022bc924-ac57-442d-80c9-df042b73ad87"
        },
        {
          "name": "Test group 18",
          "groupId": "bbfc6fc9-96db-4e66-88f4-c55b08298272",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=bbfc6fc9-96db-4e66-88f4-c55b08298272"
        },
        {
          "name": "Test group 19",
          "groupId": "3c4fef5d-9721-4f20-9a68-346d222de3cf",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=3c4fef5d-9721-4f20-9a68-346d222de3cf"
        },
        {
          "name": "Test group 2",
          "groupId": "5ddb26f1-2d31-414a-ac34-b2d6de38805d",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=5ddb26f1-2d31-414a-ac34-b2d6de38805d"
        },
        {
          "name": "Test group 3",
          "groupId": "638aa1ad-8707-4d56-9361-f5959b6c4785",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=638aa1ad-8707-4d56-9361-f5959b6c4785"
        },
        {
          "name": "Test group 4",
          "groupId": "532554e0-43be-4eca-9186-b417dcf38547",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=532554e0-43be-4eca-9186-b417dcf38547"
        },
        {
          "name": "Test group 5",
          "groupId": "6b663734-85b6-4185-8fb2-9ac27709b3aa",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=6b663734-85b6-4185-8fb2-9ac27709b3aa"
        },
        {
          "name": "Test group 6",
          "groupId": "2d4af5cf-cd34-4e78-9445-abc000cdd5cc",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=2d4af5cf-cd34-4e78-9445-abc000cdd5cc"
        },
        {
          "name": "Test group 7",
          "groupId": "e8a97909-d807-4f79-8548-1f2c156ae6f0",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=e8a97909-d807-4f79-8548-1f2c156ae6f0"
        },
        {
          "name": "Test group 8",
          "groupId": "3ee851e7-6688-495a-a6f6-737e85a23878",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=3ee851e7-6688-495a-a6f6-737e85a23878"
        },
        {
          "name": "Test group 9",
          "groupId": "af27d0b1-4378-443f-9a6d-f878848b144a",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=af27d0b1-4378-443f-9a6d-f878848b144a"
        }
      ]
    },
    "applicationRoles": {
      "size": 1,
      "items": [
        {
          "key": "jira-software",
          "name": "Jira Software"
        }
      ]
    },
    "expand": "groups,applicationRoles"
  },
  {
    "self": "https://airbyteio.atlassian.net/rest/api/2/user?accountId=557058:f58131cb-b67d-43c7-b30d-6b58d40bd077",
    "accountId": "557058:f58131cb-b67d-43c7-b30d-6b58d40bd077",
    "accountType": "app",
    "avatarUrls": {
      "48x48": "https://secure.gravatar.com/avatar/600529a9c8bfef89daa848e6db28ed2d?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAJ-0.png",
      "24x24": "https://secure.gravatar.com/avatar/600529a9c8bfef89daa848e6db28ed2d?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAJ-0.png",
      "16x16": "https://secure.gravatar.com/avatar/600529a9c8bfef89daa848e6db28ed2d?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAJ-0.png",
      "32x32": "https://secure.gravatar.com/avatar/600529a9c8bfef89daa848e6db28ed2d?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FAJ-0.png"
    },
    "displayName": "Automation for Jira",
    "active": true,
    "timeZone": "America/Los_Angeles",
    "locale": "en_US",
    "groups": {
      "size": 2,
      "items": [
        {
          "name": "atlassian-addons-admin",
          "groupId": "90b9ffb1-ed26-4b5e-af59-8f684900ce83",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=90b9ffb1-ed26-4b5e-af59-8f684900ce83"
        },
        {
          "name": "jira-software-users",
          "groupId": "4452b254-035d-469a-a422-1f4666dce50e",
          "self": "https://airbyteio.atlassian.net/rest/api/2/group?groupId=4452b254-035d-469a-a422-1f4666dce50e"
        }
      ]
    },
    "applicationRoles": {
      "size": 1,
      "items": [
        {
          "key": "jira-software",
          "name": "Jira Software"
        }
      ]
    },
    "expand": "groups,applicationRoles"
  }
]

=== Encore-Post-Sales/airbyte-magnify/airbyte-integrations/connectors/source-jira-data-center/unit_tests/responses/users.json
[
  {
    "self": "https://airbyteio.atlassian.net/rest/api/2/user?accountId=5fc9e78d2730d800760becc4",
    "accountId": "1",
    "accountType": "atlassian",
    "emailAddress": "integration-test@airbyte.io",
    "avatarUrls": {
      "48x48": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "24x24": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "16x16": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "32x32": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png"
    }
  },
  {
    "self": "https://airbyteio.atlassian.net/rest/api/2/user?accountId=5fc9e78d2730d800760becc4",
    "accountId": "2",
    "accountType": "atlassian",
    "emailAddress": "integration-test@airbyte.io",
    "avatarUrls": {
      "48x48": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "24x24": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "16x16": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png",
      "32x32": "https://secure.gravatar.com/avatar/0a7841feac7218131ce7b427283c24ef?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FIT-5.png"
    }
  }
]
